import Head from 'next/head';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import styled from 'styled-components';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatsapp Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Sidebar />
    <NadaContainer>
    <h1>Ninguém por aqui...</h1>
    <img style={{ height: '80%', width: '80%', marginBottom: '-20%', marginTop: '-20%'}} src="https://usagif.com/wp-content/uploads/2022/hqgif/ghost-50-pixel-ghost-transparent-background.gif" />
    <h1>Clique em uma conversa na barra lateral,</h1><h1>ou comece uma em </h1><h1>"comece uma nova conversa"</h1>
    </NadaContainer>
    </>
  )
}

const NadaContainer = styled.div`
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-25%, -50%);
  height: 700px;
  width: 700px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  text-align: center;
  gap: 5%;
  margin-top: -2%;
`